[features]
seeds = true
skip-lint = false

[toolchain]
anchor_version = "0.31.1"
solana_version = "3.1.13"

[programs.localnet]
agentproof = "GdJFUktyh4SFxDfqeFE33KvXf5u6TMrDzmMs5Je2NKjG"

[programs.devnet]
agentproof = "GdJFUktyh4SFxDfqeFE33KvXf5u6TMrDzmMs5Je2NKjG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
